kind: pipeline
type: docker
name: default

# Chỉ chạy khi có push hoặc merge vào release/qc
trigger:
  branch:
    - release/qc
  event:
    - push
    - pull_request

steps:
- name: test
  image: golang:1.21
  commands:
  - go mod download
  - go test ./...

- name: build
  image: golang:1.21
  commands:
  - CGO_ENABLED=0 GOOS=linux go build -o app
  - chmod +x app
  
- name: deploy
  image: appleboy/drone-scp
  settings:
    host: 
      from_secret: server_host
    username:
      from_secret: server_username
    password:
      from_secret: server_password
    port: 22
    target: /path/to/your/app/directory
    source: app